# -*- coding: utf-8 -*-
"""Ice cream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wm8rjS9kjKG2XUi1uDgAnnpVk_YFKbBH
"""

seasonal_flavors=["Mango Matcha","Blueberry-Apricot","Pumpkin Caramel","Lavender Honey","Peach Mocha"]
Ingredient_inventory=["Milk","Egg","Condensed Milk","Sugar","Honey","Mango","Matcha","Blueberry","Apricot","Pumpkin ","Caramel","Lavender","Peach","Coffee powder"]
Allergies=["Lactose Intolerance","Egg Allergy","Pollen Allergy","Caffeine Sensitivity"] # Possible allergies
customer_sugg = []
cart = []

# Customers
for i in range(1,4):
  print(f"Customer {i}:")
  cart =[]
  flavor =input("Enter preferred flavor :")
  if flavor in seasonal_flavors:
    cart.append(flavor)
  else:
    print("This flavor is unavailable. We're sorry for the inconvenience")
    sugg = input("New flavor combination suggestion ? (yes/no)")
    if sugg.lower() == "yes":
      new_sugg = input("Enter new suggestion")
      customer_sugg[i-1]= new_sugg
  allergy_status = input("Do you have any allergies ? (yes/no)")
  if allergy_status.lower() == "yes":
    new_allergy = input("Enter your allergy: ")
    if new_allergy in Allergies:
      print("Already listed")
    else:
      Allergies.append(new_allergy)
      print("New allergy added")
  print("Cart Items:",cart)